export default {
  MIDWAY_API_PATH: '/midway/api',
  MIDWAY_DEFAULT_MOCKED_DATA_LOC: 'resources/mocked-data',
  MIDWAY_PRIVATE_KEY_FILE: 'key.pem',
  MIDWAY_CERTIFICATE_FILE: 'cert.pem',
  MIDWAY_CERT_FOLDER_NAME: '.certs',
  MOCKED_RESPONSE: 'mocked-response',
  DEFAULT: 'default',
  DEFAULT_VARIANT: 'default',
  COLLECT_USAGE_METRICS: true,
  DEFAULT_SESSION: 'default',
  NOT_FOUND: 404,
  MOCK_PORT: 'mockPort',
  VARIANT: 'variant',
  FIXTURE: 'fixture',
  KAIROS_DB_URL: 'metricsDB',
  NOT_AVAILABLE: 'n/a',
  HTTP_PORT: 'httpPort',
  HTTPS_PORT: 'httpsPort',
  PROJECT: 'project',
  MULTI_REPOS_PATH: './repos',
  SESSIONID: 'sessionid'
};